export const data = [
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2023-05-15",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2023-06-02",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2020-05-28",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2020-06-10",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2020-05-20",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2020-06-05",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2019-05-17",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10LPA",
    position: "Biomedical Researcher",
    placement_date: "2019-06-12",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2019-05-30",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2019-06-08",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2023-05-25",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10LPA",
    position: "Financial Analyst",
    placement_date: "2023-06-15",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2023-05-23",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2023-06-18",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2023-05-19",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2023-06-20",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2023-05-22",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2023-06-25",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2023-05-24",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2023-06-30",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2023-05-27",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2023-07-02",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2023-06-01",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2023-07-05",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2023-05-26",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2023-07-10",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2023-05-29",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2023-07-15",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2023-05-21",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2023-07-20",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2018-05-15",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2018-06-02",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2018-05-28",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2018-06-10",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2018-05-20",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2020-06-05",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2020-05-17",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10LPA",
    position: "Biomedical Researcher",
    placement_date: "2020-06-12",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2020-05-30",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2020-06-08",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2020-05-25",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10LPA",
    position: "Financial Analyst",
    placement_date: "2020-06-15",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2020-05-23",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2022-06-18",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2022-05-19",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2022-06-20",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2022-05-22",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2022-06-25",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2022-05-24",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2022-06-30",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2022-05-27",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2022-07-02",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2022-06-01",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2022-07-05",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2022-05-26",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2022-07-10",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2022-05-29",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2022-07-15",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2022-05-21",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "12LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2022-07-20",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2023-05-15",
    year_of_passing: 2023,
    department: "EEE",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2023-06-02",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2023-05-28",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2019-06-10",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2019-05-20",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2023-06-05",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2023-05-17",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10.6LPA",
    position: "Biomedical Researcher",
    placement_date: "2023-06-12",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2020-05-30",
    year_of_passing: 2020,
    department: "ECE",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2020-06-08",
    year_of_passing: 2020,
    department: "ECE",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2018-05-25",
    year_of_passing: 2018,
    department: "ECE",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2019-06-15",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2019-05-23",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2019-06-18",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10.6LPA",
    position: "Medical Researcher",
    placement_date: "2021-05-19",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2021-06-20",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2021-05-22",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2021-06-25",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2021-05-24",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2021-06-30",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2021-05-27",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2021-07-02",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2021-06-01",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2021-07-05",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2021-05-26",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2021-07-10",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2021-05-29",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2021-07-15",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10.6LPA",
    position: "Medical Researcher",
    placement_date: "2021-05-21",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "12LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2021-07-20",
    year_of_passing: 2021,
    department: "AIML",
  },
];
