export const data = [
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2023-05-15",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2023-06-02",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2020-05-28",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2020-06-10",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2020-05-20",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2020-06-05",
    year_of_passing: 2020,
    department: "CSE",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2019-05-17",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10LPA",
    position: "Biomedical Researcher",
    placement_date: "2019-06-12",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2019-05-30",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2019-06-08",
    year_of_passing: 2019,
    department: "CSE",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2023-05-25",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10LPA",
    position: "Financial Analyst",
    placement_date: "2023-06-15",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2023-05-23",
    year_of_passing: 2023,
    department: "CSE",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2023-06-18",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2023-05-19",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2023-06-20",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2023-05-22",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2023-06-25",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2023-05-24",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2023-06-30",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2023-05-27",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2023-07-02",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2023-06-01",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2023-07-05",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2023-05-26",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2023-07-10",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2023-05-29",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2023-07-15",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2023-05-21",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2023-07-20",
    year_of_passing: 2023,
    department: "IT",
  },
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2018-05-15",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2018-06-02",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2018-05-28",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2018-06-10",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2018-05-20",
    year_of_passing: 2018,
    department: "IT",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2020-06-05",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2020-05-17",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10LPA",
    position: "Biomedical Researcher",
    placement_date: "2020-06-12",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2020-05-30",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2020-06-08",
    year_of_passing: 2020,
    department: "IT",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2020-05-25",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10LPA",
    position: "Financial Analyst",
    placement_date: "2020-06-15",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2020-05-23",
    year_of_passing: 2020,
    department: "MECH",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2022-06-18",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2022-05-19",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2022-06-20",
    year_of_passing: 2022,
    department: "MECH",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2022-05-22",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2022-06-25",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2022-05-24",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2022-06-30",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2022-05-27",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2022-07-02",
    year_of_passing: 2022,
    department: "CIVIL",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2022-06-01",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2022-07-05",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2022-05-26",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2022-07-10",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2022-05-29",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2022-07-15",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10LPA",
    position: "Medical Researcher",
    placement_date: "2022-05-21",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "12LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2022-07-20",
    year_of_passing: 2022,
    department: "EEE",
  },
  {
    student_id: "1001",
    student_name: "John Doe",
    company_name: "TechCo Solutions",
    ctc: "10LPA",
    position: "Full Stack Developer",
    placement_date: "2023-05-15",
    year_of_passing: 2023,
    department: "EEE",
  },
  {
    student_id: "1002",
    student_name: "Alice Smith",
    company_name: "DataTech Innovations",
    ctc: "9.5LPA",
    position: "Data Analyst",
    placement_date: "2023-06-02",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1003",
    student_name: "Ella Johnson",
    company_name: "FinTech Corp",
    ctc: "12LPA",
    position: "Financial Analyst",
    placement_date: "2023-05-28",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1004",
    student_name: "David Wilson",
    company_name: "CyberSec Systems",
    ctc: "11.5LPA",
    position: "Cybersecurity Engineer",
    placement_date: "2019-06-10",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1005",
    student_name: "Sarah Brown",
    company_name: "HealthTech Innovations",
    ctc: "9LPA",
    position: "Software Engineer",
    placement_date: "2019-05-20",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1006",
    student_name: "Michael Davis",
    company_name: "EduSoft Solutions",
    ctc: "10.5LPA",
    position: "Educational Software Developer",
    placement_date: "2023-06-05",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1007",
    student_name: "Olivia Wilson",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2023-05-17",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1008",
    student_name: "James Anderson",
    company_name: "BioPharma Inc.",
    ctc: "10.6LPA",
    position: "Biomedical Researcher",
    placement_date: "2023-06-12",
    year_of_passing: 2023,
    department: "ECE",
  },
  {
    student_id: "1009",
    student_name: "Sophia Miller",
    company_name: "AI Innovators",
    ctc: "12.5LPA",
    position: "AI Researcher",
    placement_date: "2020-05-30",
    year_of_passing: 2020,
    department: "ECE",
  },
  {
    student_id: "1010",
    student_name: "William Jones",
    company_name: "AutoTech Systems",
    ctc: "9LPA",
    position: "Automotive Engineer",
    placement_date: "2020-06-08",
    year_of_passing: 2020,
    department: "ECE",
  },
  {
    student_id: "1011",
    student_name: "Emily Taylor",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2018-05-25",
    year_of_passing: 2018,
    department: "ECE",
  },
  {
    student_id: "1012",
    student_name: "Liam Brown",
    company_name: "Financial Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2019-06-15",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1013",
    student_name: "Emma Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2019-05-23",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1014",
    student_name: "Noah Johnson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2019-06-18",
    year_of_passing: 2019,
    department: "ECE",
  },
  {
    student_id: "1015",
    student_name: "Ava Wilson",
    company_name: "HealthCare Solutions",
    ctc: "10.6LPA",
    position: "Medical Researcher",
    placement_date: "2021-05-19",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1016",
    student_name: "Mason Smith",
    company_name: "CyberGuard Inc.",
    ctc: "11LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2021-06-20",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1017",
    student_name: "Harper Martin",
    company_name: "DataMasters Corp",
    ctc: "9LPA",
    position: "Data Scientist",
    placement_date: "2021-05-22",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1018",
    student_name: "Jackson Garcia",
    company_name: "AutoTech Innovations",
    ctc: "12LPA",
    position: "Automotive Engineer",
    placement_date: "2021-06-25",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1019",
    student_name: "Evelyn Lopez",
    company_name: "FinTech Wizards",
    ctc: "10.6LPA",
    position: "Financial Analyst",
    placement_date: "2021-05-24",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1020",
    student_name: "Aiden Hernandez",
    company_name: "TechGenius Solutions",
    ctc: "13.5LPA",
    position: "Software Architect",
    placement_date: "2021-06-30",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1021",
    student_name: "Sofia White",
    company_name: "GreenEnergy Corp",
    ctc: "11LPA",
    position: "Environmental Analyst",
    placement_date: "2021-05-27",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1022",
    student_name: "Lucas Martinez",
    company_name: "BioPharma Inc.",
    ctc: "10.9LPA",
    position: "Biomedical Researcher",
    placement_date: "2021-07-02",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1023",
    student_name: "Lily Taylor",
    company_name: "AI Innovators",
    ctc: "12LPA",
    position: "AI Researcher",
    placement_date: "2021-06-01",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1024",
    student_name: "Grayson Brown",
    company_name: "AutoTech Systems",
    ctc: "9.5LPA",
    position: "Automotive Engineer",
    placement_date: "2021-07-05",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1025",
    student_name: "Liam Johnson",
    company_name: "SpaceTech Innovations",
    ctc: "13LPA",
    position: "Astronautical Engineer",
    placement_date: "2021-05-26",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1026",
    student_name: "Avery Smith",
    company_name: "Financial Wizards",
    ctc: "10.4LPA",
    position: "Financial Analyst",
    placement_date: "2021-07-10",
    year_of_passing: 2021,
    department: "CSE",
  },
  {
    student_id: "1027",
    student_name: "Scarlett Davis",
    company_name: "TechMasters Inc.",
    ctc: "11LPA",
    position: "Software Engineer",
    placement_date: "2021-05-29",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1028",
    student_name: "James Wilson",
    company_name: "GreenTech Innovations",
    ctc: "9LPA",
    position: "Environmental Analyst",
    placement_date: "2021-07-15",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1029",
    student_name: "Ella Harris",
    company_name: "HealthCare Solutions",
    ctc: "10.6LPA",
    position: "Medical Researcher",
    placement_date: "2021-05-21",
    year_of_passing: 2021,
    department: "AIML",
  },
  {
    student_id: "1030",
    student_name: "Logan Brown",
    company_name: "CyberGuard Inc.",
    ctc: "12LPA",
    position: "Cybersecurity Analyst",
    placement_date: "2021-07-20",
    year_of_passing: 2021,
    department: "AIML",
  },
];

// export const data = [
  
//   {
//     student_id: "1001",
//     student_name: "Student 1",
//     company_name: "Web Gurus",
//     ctc: "7LPA",
//     position: "Data Analyst",
//     placement_date: "2023-12-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1002",
//     student_name: "Student 2",
//     company_name: "InnoVision",
//     ctc: "18LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1003",
//     student_name: "Student 3",
//     company_name: "Alpha Technologies",
//     ctc: "10LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-12-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1004",
//     student_name: "Student 4",
//     company_name: "Cyber Systems",
//     ctc: "13LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-20",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1005",
//     student_name: "Student 5",
//     company_name: "InnoSolutions",
//     ctc: "9LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-08-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1006",
//     student_name: "Student 6",
//     company_name: "Web Wizards",
//     ctc: "10LPA",
//     position: "Data Analyst",
//     placement_date: "2023-09-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1007",
//     student_name: "Student 7",
//     company_name: "Infinite Innovations",
//     ctc: "10LPA",
//     position: "Data Analyst",
//     placement_date: "2023-06-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1008",
//     student_name: "Student 8",
//     company_name: "Epic Software",
//     ctc: "5LPA",
//     position: "Data Analyst",
//     placement_date: "2023-01-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1009",
//     student_name: "Student 9",
//     company_name: "Digital Dynamics",
//     ctc: "6LPA",
//     position: "UX Designer",
//     placement_date: "2023-02-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1010",
//     student_name: "Student 10",
//     company_name: "TechCo Solutions",
//     ctc: "20LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-02-16",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1011",
//     student_name: "Student 11",
//     company_name: "InnoSolutions",
//     ctc: "12LPA",
//     position: "Software Engineer",
//     placement_date: "2023-11-19",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1012",
//     student_name: "Student 12",
//     company_name: "InnoGenius",
//     ctc: "5LPA",
//     position: "UX Designer",
//     placement_date: "2023-06-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1013",
//     student_name: "Student 13",
//     company_name: "Code Innovators",
//     ctc: "7LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-02-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1014",
//     student_name: "Student 14",
//     company_name: "Tech Innovators",
//     ctc: "16LPA",
//     position: "Data Analyst",
//     placement_date: "2023-02-23",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1015",
//     student_name: "Student 15",
//     company_name: "Code Crafters",
//     ctc: "12LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-09-16",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1016",
//     student_name: "Student 16",
//     company_name: "Web Gurus",
//     ctc: "13LPA",
//     position: "Data Analyst",
//     placement_date: "2023-05-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1017",
//     student_name: "Student 17",
//     company_name: "Web Wizards",
//     ctc: "12LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-05-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1018",
//     student_name: "Student 18",
//     company_name: "Quantum Innovations",
//     ctc: "16LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-03-13",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1019",
//     student_name: "Student 19",
//     company_name: "Swift Solutions",
//     ctc: "6LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-11-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1020",
//     student_name: "Student 20",
//     company_name: "Epic Software",
//     ctc: "17LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-02-10",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1021",
//     student_name: "Student 21",
//     company_name: "Binary Solutions",
//     ctc: "15LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-08-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1022",
//     student_name: "Student 22",
//     company_name: "Future Systems",
//     ctc: "9LPA",
//     position: "Data Analyst",
//     placement_date: "2023-03-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1023",
//     student_name: "Student 23",
//     company_name: "Innovatech",
//     ctc: "12LPA",
//     position: "Data Analyst",
//     placement_date: "2023-01-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1024",
//     student_name: "Student 24",
//     company_name: "Swift Solutions",
//     ctc: "8LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-06-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1025",
//     student_name: "Student 25",
//     company_name: "Future Systems",
//     ctc: "7LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1026",
//     student_name: "Student 26",
//     company_name: "Digital Sapiens",
//     ctc: "16LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-06-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1027",
//     student_name: "Student 27",
//     company_name: "Cyber Systems",
//     ctc: "14LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-07-10",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1028",
//     student_name: "Student 28",
//     company_name: "Binary Solutions",
//     ctc: "16LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-06-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1029",
//     student_name: "Student 29",
//     company_name: "Nexa Labs",
//     ctc: "5LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-14",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1030",
//     student_name: "Student 30",
//     company_name: "Nexa Labs",
//     ctc: "20LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-07-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1031",
//     student_name: "Student 31",
//     company_name: "Cyber Systems",
//     ctc: "7LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-01-27",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1032",
//     student_name: "Student 32",
//     company_name: "InnoSolutions",
//     ctc: "12LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-12-02",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1033",
//     student_name: "Student 33",
//     company_name: "Data Systems",
//     ctc: "6LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-03-21",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1034",
//     student_name: "Student 34",
//     company_name: "TechCo Solutions",
//     ctc: "6LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-08-06",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1035",
//     student_name: "Student 35",
//     company_name: "Web Wizards",
//     ctc: "9LPA",
//     position: "Data Analyst",
//     placement_date: "2023-02-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1036",
//     student_name: "Student 36",
//     company_name: "Tech Innovators",
//     ctc: "10LPA",
//     position: "Data Analyst",
//     placement_date: "2023-04-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1037",
//     student_name: "Student 37",
//     company_name: "Future Systems",
//     ctc: "9LPA",
//     position: "Data Analyst",
//     placement_date: "2023-02-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1038",
//     student_name: "Student 38",
//     company_name: "Tech Innovators",
//     ctc: "16LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-04-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1039",
//     student_name: "Student 39",
//     company_name: "Digital Dynamics",
//     ctc: "7LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-12-23",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1040",
//     student_name: "Student 40",
//     company_name: "Apex Solutions",
//     ctc: "19LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-19",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1041",
//     student_name: "Student 41",
//     company_name: "Future Systems",
//     ctc: "13LPA",
//     position: "UX Designer",
//     placement_date: "2023-12-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1042",
//     student_name: "Student 42",
//     company_name: "Alpha Technologies",
//     ctc: "12LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-03-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1043",
//     student_name: "Student 43",
//     company_name: "Code Crafters",
//     ctc: "17LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-11-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1044",
//     student_name: "Student 44",
//     company_name: "InnoVision",
//     ctc: "16LPA",
//     position: "Software Engineer",
//     placement_date: "2023-04-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1045",
//     student_name: "Student 45",
//     company_name: "InnoGenius",
//     ctc: "8LPA",
//     position: "UX Designer",
//     placement_date: "2023-11-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1046",
//     student_name: "Student 46",
//     company_name: "Alpha Technologies",
//     ctc: "9LPA",
//     position: "Data Analyst",
//     placement_date: "2023-02-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1047",
//     student_name: "Student 47",
//     company_name: "Swift Solutions",
//     ctc: "8LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-08-14",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1048",
//     student_name: "Student 48",
//     company_name: "Code Innovators",
//     ctc: "6LPA",
//     position: "UX Designer",
//     placement_date: "2023-05-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1049",
//     student_name: "Student 49",
//     company_name: "Smart Systems",
//     ctc: "7LPA",
//     position: "UX Designer",
//     placement_date: "2023-03-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1050",
//     student_name: "Student 50",
//     company_name: "Future Systems",
//     ctc: "16LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-03-27",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1051",
//     student_name: "Student 51",
//     company_name: "Web Gurus",
//     ctc: "5LPA",
//     position: "Software Engineer",
//     placement_date: "2023-05-09",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1052",
//     student_name: "Student 52",
//     company_name: "InnoSolutions",
//     ctc: "11LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-01-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1053",
//     student_name: "Student 53",
//     company_name: "Quantum Innovations",
//     ctc: "16LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-03-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1054",
//     student_name: "Student 54",
//     company_name: "Web Wizards",
//     ctc: "12LPA",
//     position: "UX Designer",
//     placement_date: "2023-09-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1055",
//     student_name: "Student 55",
//     company_name: "Tech Titans",
//     ctc: "6LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-11-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1056",
//     student_name: "Student 56",
//     company_name: "Quantum Innovations",
//     ctc: "16LPA",
//     position: "Software Engineer",
//     placement_date: "2023-03-09",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1057",
//     student_name: "Student 57",
//     company_name: "Apex Solutions",
//     ctc: "12LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-05-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1058",
//     student_name: "Student 58",
//     company_name: "Apex Solutions",
//     ctc: "20LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-03-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1059",
//     student_name: "Student 59",
//     company_name: "Code Creations",
//     ctc: "5LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-10-02",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1060",
//     student_name: "Student 60",
//     company_name: "Digital Sapiens",
//     ctc: "12LPA",
//     position: "Software Engineer",
//     placement_date: "2023-07-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1061",
//     student_name: "Student 61",
//     company_name: "Infinite Innovations",
//     ctc: "10LPA",
//     position: "Software Engineer",
//     placement_date: "2023-11-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1062",
//     student_name: "Student 62",
//     company_name: "TechCo Solutions",
//     ctc: "20LPA",
//     position: "Data Analyst",
//     placement_date: "2023-08-24",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1063",
//     student_name: "Student 63",
//     company_name: "Innovatech",
//     ctc: "13LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-12-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1064",
//     student_name: "Student 64",
//     company_name: "TechCo Solutions",
//     ctc: "7LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-01-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1065",
//     student_name: "Student 65",
//     company_name: "Web Wizards",
//     ctc: "20LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-06-20",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1066",
//     student_name: "Student 66",
//     company_name: "Alpha Innovators",
//     ctc: "12LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-06-10",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1067",
//     student_name: "Student 67",
//     company_name: "Apex Solutions",
//     ctc: "10LPA",
//     position: "Software Engineer",
//     placement_date: "2023-11-23",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1068",
//     student_name: "Student 68",
//     company_name: "Web Gurus",
//     ctc: "14LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-02-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1069",
//     student_name: "Student 69",
//     company_name: "Epic Software",
//     ctc: "11LPA",
//     position: "UX Designer",
//     placement_date: "2023-08-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1070",
//     student_name: "Student 70",
//     company_name: "Quantum Innovations",
//     ctc: "19LPA",
//     position: "Data Analyst",
//     placement_date: "2023-03-01",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1071",
//     student_name: "Student 71",
//     company_name: "Binary Solutions",
//     ctc: "13LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1072",
//     student_name: "Student 72",
//     company_name: "Tech Titans",
//     ctc: "19LPA",
//     position: "Data Analyst",
//     placement_date: "2023-05-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1073",
//     student_name: "Student 73",
//     company_name: "InnoVision",
//     ctc: "8LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-07-24",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1074",
//     student_name: "Student 74",
//     company_name: "SoftLabs",
//     ctc: "6LPA",
//     position: "UX Designer",
//     placement_date: "2023-07-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1075",
//     student_name: "Student 75",
//     company_name: "Swift Solutions",
//     ctc: "17LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-06-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1076",
//     student_name: "Student 76",
//     company_name: "Digital Sapiens",
//     ctc: "20LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-02-16",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1077",
//     student_name: "Student 77",
//     company_name: "InnoGenius",
//     ctc: "19LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-09-25",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1078",
//     student_name: "Student 78",
//     company_name: "Smart Systems",
//     ctc: "20LPA",
//     position: "Data Analyst",
//     placement_date: "2023-01-09",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1079",
//     student_name: "Student 79",
//     company_name: "Quantum Innovations",
//     ctc: "11LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-09-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1080",
//     student_name: "Student 80",
//     company_name: "Digital Sapiens",
//     ctc: "16LPA",
//     position: "Software Engineer",
//     placement_date: "2023-07-13",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1081",
//     student_name: "Student 81",
//     company_name: "Data Systems",
//     ctc: "14LPA",
//     position: "Software Engineer",
//     placement_date: "2023-09-02",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1082",
//     student_name: "Student 82",
//     company_name: "InnoGenius",
//     ctc: "20LPA",
//     position: "Software Engineer",
//     placement_date: "2023-06-18",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1083",
//     student_name: "Student 83",
//     company_name: "TechCo Solutions",
//     ctc: "20LPA",
//     position: "UX Designer",
//     placement_date: "2023-02-19",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1084",
//     student_name: "Student 84",
//     company_name: "eTech Ventures",
//     ctc: "16LPA",
//     position: "UX Designer",
//     placement_date: "2023-02-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1085",
//     student_name: "Student 85",
//     company_name: "Digital Sapiens",
//     ctc: "15LPA",
//     position: "UX Designer",
//     placement_date: "2023-12-20",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1086",
//     student_name: "Student 86",
//     company_name: "Epic Software",
//     ctc: "15LPA",
//     position: "UX Designer",
//     placement_date: "2023-03-02",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1087",
//     student_name: "Student 87",
//     company_name: "Innovatech",
//     ctc: "12LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-06-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1088",
//     student_name: "Student 88",
//     company_name: "Apex Solutions",
//     ctc: "12LPA",
//     position: "Software Engineer",
//     placement_date: "2023-01-27",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1089",
//     student_name: "Student 89",
//     company_name: "TechCo Solutions",
//     ctc: "5LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-02-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1090",
//     student_name: "Student 90",
//     company_name: "Cyber Systems",
//     ctc: "10LPA",
//     position: "Software Engineer",
//     placement_date: "2023-04-01",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1091",
//     student_name: "Student 91",
//     company_name: "Innovatech",
//     ctc: "14LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-10-01",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1092",
//     student_name: "Student 92",
//     company_name: "Tech Titans",
//     ctc: "14LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-05-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1093",
//     student_name: "Student 93",
//     company_name: "Code Innovators",
//     ctc: "7LPA",
//     position: "UX Designer",
//     placement_date: "2023-07-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1094",
//     student_name: "Student 94",
//     company_name: "Data Systems",
//     ctc: "20LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-12-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1095",
//     student_name: "Student 95",
//     company_name: "Future Systems",
//     ctc: "16LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-01-19",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1096",
//     student_name: "Student 96",
//     company_name: "Web Wizards",
//     ctc: "9LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-05-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1097",
//     student_name: "Student 97",
//     company_name: "InnoVision",
//     ctc: "15LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-08-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1098",
//     student_name: "Student 98",
//     company_name: "Swift Solutions",
//     ctc: "10LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1099",
//     student_name: "Student 99",
//     company_name: "Data Masters",
//     ctc: "15LPA",
//     position: "UX Designer",
//     placement_date: "2023-01-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1100",
//     student_name: "Student 100",
//     company_name: "Web Wizards",
//     ctc: "13LPA",
//     position: "Software Engineer",
//     placement_date: "2023-12-24",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1101",
//     student_name: "Student 101",
//     company_name: "Tech Innovators",
//     ctc: "13LPA",
//     position: "Data Analyst",
//     placement_date: "2023-07-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1102",
//     student_name: "Student 102",
//     company_name: "InnoGenius",
//     ctc: "12LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-10-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1103",
//     student_name: "Student 103",
//     company_name: "Swift Solutions",
//     ctc: "5LPA",
//     position: "Data Analyst",
//     placement_date: "2023-06-21",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1104",
//     student_name: "Student 104",
//     company_name: "Cyber Systems",
//     ctc: "11LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-01-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1105",
//     student_name: "Student 105",
//     company_name: "Innovatech",
//     ctc: "10LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-10-02",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1106",
//     student_name: "Student 106",
//     company_name: "Binary Solutions",
//     ctc: "14LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-06-10",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1107",
//     student_name: "Student 107",
//     company_name: "Infinite Innovations",
//     ctc: "18LPA",
//     position: "UX Designer",
//     placement_date: "2023-10-06",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1108",
//     student_name: "Student 108",
//     company_name: "Infinite Innovations",
//     ctc: "16LPA",
//     position: "UX Designer",
//     placement_date: "2023-10-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1109",
//     student_name: "Student 109",
//     company_name: "Infinite Innovations",
//     ctc: "5LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-18",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1110",
//     student_name: "Student 110",
//     company_name: "Code Crafters",
//     ctc: "11LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-02-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1111",
//     student_name: "Student 111",
//     company_name: "Apex Solutions",
//     ctc: "19LPA",
//     position: "UX Designer",
//     placement_date: "2023-05-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1112",
//     student_name: "Student 112",
//     company_name: "InnoVision",
//     ctc: "8LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-08-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1113",
//     student_name: "Student 113",
//     company_name: "Alpha Innovators",
//     ctc: "17LPA",
//     position: "UX Designer",
//     placement_date: "2023-01-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1114",
//     student_name: "Student 114",
//     company_name: "Tech Innovators",
//     ctc: "6LPA",
//     position: "Data Analyst",
//     placement_date: "2023-05-20",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1115",
//     student_name: "Student 115",
//     company_name: "Code Crafters",
//     ctc: "5LPA",
//     position: "UX Designer",
//     placement_date: "2023-08-16",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1116",
//     student_name: "Student 116",
//     company_name: "InnoSolutions",
//     ctc: "19LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-08-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1117",
//     student_name: "Student 117",
//     company_name: "Innovatech",
//     ctc: "8LPA",
//     position: "Software Engineer",
//     placement_date: "2023-03-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1118",
//     student_name: "Student 118",
//     company_name: "Swift Solutions",
//     ctc: "11LPA",
//     position: "UX Designer",
//     placement_date: "2023-12-08",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1119",
//     student_name: "Student 119",
//     company_name: "Alpha Technologies",
//     ctc: "5LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-11-28",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1120",
//     student_name: "Student 120",
//     company_name: "Binary Solutions",
//     ctc: "13LPA",
//     position: "UX Designer",
//     placement_date: "2023-03-23",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1121",
//     student_name: "Student 121",
//     company_name: "Infinite Innovations",
//     ctc: "17LPA",
//     position: "UX Designer",
//     placement_date: "2023-01-24",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1122",
//     student_name: "Student 122",
//     company_name: "Digital Dynamics",
//     ctc: "8LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-10-13",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1123",
//     student_name: "Student 123",
//     company_name: "Data Masters",
//     ctc: "14LPA",
//     position: "Data Analyst",
//     placement_date: "2023-10-17",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1124",
//     student_name: "Student 124",
//     company_name: "Quantum Innovations",
//     ctc: "5LPA",
//     position: "UX Designer",
//     placement_date: "2023-01-05",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1125",
//     student_name: "Student 125",
//     company_name: "Nexa Labs",
//     ctc: "18LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-03-15",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1126",
//     student_name: "Student 126",
//     company_name: "Apex Solutions",
//     ctc: "8LPA",
//     position: "Data Analyst",
//     placement_date: "2023-01-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1127",
//     student_name: "Student 127",
//     company_name: "Apex Solutions",
//     ctc: "16LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-24",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1128",
//     student_name: "Student 128",
//     company_name: "Data Systems",
//     ctc: "18LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-07-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1129",
//     student_name: "Student 129",
//     company_name: "Data Systems",
//     ctc: "10LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1130",
//     student_name: "Student 130",
//     company_name: "Smart Systems",
//     ctc: "19LPA",
//     position: "Data Analyst",
//     placement_date: "2023-11-19",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1131",
//     student_name: "Student 131",
//     company_name: "TechCo Solutions",
//     ctc: "8LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-07-03",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1132",
//     student_name: "Student 132",
//     company_name: "Web Gurus",
//     ctc: "17LPA",
//     position: "UX Designer",
//     placement_date: "2023-12-18",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1133",
//     student_name: "Student 133",
//     company_name: "Data Masters",
//     ctc: "16LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-05-11",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1134",
//     student_name: "Student 134",
//     company_name: "Code Creations",
//     ctc: "17LPA",
//     position: "Data Analyst",
//     placement_date: "2023-05-06",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1135",
//     student_name: "Student 135",
//     company_name: "InnoVision",
//     ctc: "15LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-01-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1136",
//     student_name: "Student 136",
//     company_name: "Tech Titans",
//     ctc: "5LPA",
//     position: "Data Analyst",
//     placement_date: "2023-01-12",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1137",
//     student_name: "Student 137",
//     company_name: "TechCo Solutions",
//     ctc: "6LPA",
//     position: "Frontend Developer",
//     placement_date: "2023-05-22",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1138",
//     student_name: "Student 138",
//     company_name: "Tech Innovators",
//     ctc: "20LPA",
//     position: "DevOps Engineer",
//     placement_date: "2023-04-07",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1139",
//     student_name: "Student 139",
//     company_name: "Apex Solutions",
//     ctc: "11LPA",
//     position: "UX Designer",
//     placement_date: "2023-01-26",
//     year_of_passing: 2023,
//     department: "IT",
//   },
//   {
//     student_id: "1140",
//     student_name: "Student 140",
//     company_name: "Apex Solutions",
//     ctc: "10LPA",
//     position: "Full Stack Developer",
//     placement_date: "2023-10-04",
//     year_of_passing: 2023,
//     department: "IT",
//   },
// ];
